### ISSUE TITLE
Using Topsoil as a library, setData method of Chart throws JavaFX error

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Topsoil#123]
myChart.setData(vc) // where vc is a variable context and myChart is ErrorEllipseChart, line 88 reported below

gives:

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class javafx.scene.web.WebEngine
	at javafx.scene.web.WebView.<init>(WebView.java:271)
	at org.cirdles.topsoil.chart.JavaScriptChart.initializeWebViewIfNeeded(JavaScriptChart.java:252)
	at org.cirdles.topsoil.chart.JavaScriptChart.setData(JavaScriptChart.java:303)
	at org.earthtime.UPb_Redux.dateInterpretation.TestTopsoil.<init>(TestTopsoil.java:88)

**Comment by johnzeringue** [comment]
@bowring, check out my pull request and see if that fixes things.
